### ISSUE TITLE
np.concatenate dimensionality error

### ISSUE THREAD

**Issue by JoeChengYT** [DLR-RM/rl-baselines3-zoo#199]
I was trying to train an agent in gym_donkey env, the simulator did load the car but  it was not running.
The command that I used ```python train.py --algo tqc --env donkey-mountain-track-v0 ```
```Traceback (most recent call last):
  File "train.py", line 222, in <module>
    model = exp_manager.setup_experiment()
  File "/home/joe/rl-baselines3-zoo/utils/exp_manager.py", line 168, in setup_experiment
    self.create_callbacks()
  File "/home/joe/rl-baselines3-zoo/utils/exp_manager.py", line 429, in create_callbacks
    self.create_envs(self.n_eval_envs, eval_env=True),
  File "/home/joe/rl-baselines3-zoo/utils/exp_manager.py", line 523, in create_envs
    monitor_kwargs=monitor_kwargs,
  File "/home/joe/miniconda3/envs/rl/lib/python3.7/site-packages/stable_baselines3/common/env_util.py", line 105, in make_vec_env
    return vec_env_cls([make_env(i + start_index) for i in range(n_envs)], **vec_env_kwargs)
  File "/home/joe/miniconda3/envs/rl/lib/python3.7/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 25, in __init__
    self.envs = [fn() for fn in env_fns]
  File "/home/joe/miniconda3/envs/rl/lib/python3.7/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 25, in <listcomp>
    self.envs = [fn() for fn in env_fns]
  File "/home/joe/miniconda3/envs/rl/lib/python3.7/site-packages/stable_baselines3/common/env_util.py", line 95, in _init
    env = wrapper_class(env, **wrapper_kwargs)
  File "/home/joe/rl-baselines3-zoo/utils/utils.py", line 120, in wrap_env
    env = wrapper_class(env, **kwargs)
  File "/home/joe/rl-baselines3-zoo/utils/wrappers.py", line 250, in __init__
    low = np.concatenate((low_obs, low_action))
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 1 dimension(s)```

**Comment by araffin** [comment]
Hello,
please fill in the custom env template completely: https://github.com/DLR-RM/stable-baselines3/blob/master/.github/ISSUE_TEMPLATE/custom_env.md

**Comment by JoeChengYT** [comment]
I am sorry. There was something wrong about my Docker image. It is now fixed. Sorry for the bother.
