### ISSUE TITLE
ValueError: all the input arrays must have same number of dimensions

### ISSUE THREAD

**Issue by ebadi** [DLR-RM/rl-baselines3-zoo#205]
**Describe the bug**
It is not possible to follow the instruction as described in the video [DonkeyCar Simulator: Setup and Reinforcement Learning Training](https://www.youtube.com/watch?v=ngK33h00iBE). Maybe relevant to #199. 

**Code example**
```
~/d/rl-baselines3-zoo (feat/offline-RL) [2]> python3 train.py --algo tqc --env donkey-generated-track-v0 --eval-freq -1  --save-freq 20000
pygame 2.0.0.dev6 (SDL 2.0.10, python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
========== donkey-generated-track-v0 ==========
Seed: 1178248778
Default hyperparameters for environment (ones being tuned will be overridden):
OrderedDict([('batch_size', 256),
             ('buffer_size', 200000),
             ('callback',
              [{'utils.callbacks.ParallelTrainCallback': {'gradient_steps': 200}}]),
             ('ent_coef', 'auto'),
             ('env_wrapper',
              [{'gym.wrappers.time_limit.TimeLimit': {'max_episode_steps': 10000}},
               {'utils.wrappers.HistoryWrapper': {'horizon': 2}}]),
             ('gamma', 0.99),
             ('gradient_steps', 256),
             ('learning_rate', 0.00073),
             ('learning_starts', 5000),
             ('n_timesteps', 2000000.0),
             ('normalize', "{'norm_obs': True, 'norm_reward': False}"),
             ('policy', 'MlpPolicy'),
             ('policy_kwargs',
              'dict(log_std_init=-3, net_arch=[256, 256], n_critics=2)'),
             ('sde_sample_freq', 16),
             ('tau', 0.02),
             ('train_freq', 200),
             ('use_sde', True),
             ('use_sde_at_warmup', True)])
Using 1 environments
starting DonkeyGym env
Setting default: start_delay 5.0
Setting default: max_cte 5.0
Setting default: frame_skip 1
Setting default: cam_resolution (120, 160, 3)
Setting default: log_level 20
Setting default: host localhost
Setting default: port 9091
INFO:gym_donkeycar.core.client:connecting to localhost:9091 
/home/wave/.local/lib/python3.8/site-packages/gym/logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))
WARNING:gym_donkeycar.envs.donkey_sim:waiting for sim to start..
INFO:gym_donkeycar.envs.donkey_sim:on need car config
Traceback (most recent call last):
  File "train.py", line 220, in <module>
    model = exp_manager.setup_experiment()
  File "/home/wave/donkey/rl-baselines3-zoo/utils/exp_manager.py", line 173, in setup_experiment
    env = self.create_envs(n_envs, no_log=False)
  File "/home/wave/donkey/rl-baselines3-zoo/utils/exp_manager.py", line 522, in create_envs
    env = make_vec_env(
  File "/home/wave/.local/lib/python3.8/site-packages/stable_baselines3/common/env_util.py", line 105, in make_vec_env
    return vec_env_cls([make_env(i + start_index) for i in range(n_envs)], **vec_env_kwargs)
  File "/home/wave/.local/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 25, in __init__
    self.envs = [fn() for fn in env_fns]
  File "/home/wave/.local/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 25, in <listcomp>
    self.envs = [fn() for fn in env_fns]
  File "/home/wave/.local/lib/python3.8/site-packages/stable_baselines3/common/env_util.py", line 95, in _init
    env = wrapper_class(env, **wrapper_kwargs)
  File "/home/wave/donkey/rl-baselines3-zoo/utils/utils.py", line 121, in wrap_env
    env = wrapper_class(env, **kwargs)
  File "/home/wave/donkey/rl-baselines3-zoo/utils/wrappers.py", line 250, in __init__
    low = np.concatenate((low_obs, low_action))
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 1 dimension(s)
```
**System Info**
Describe the characteristic of your environment:
 * Describe how Stable Baselines3 was installed (pip, docker, source, ...) : 
 ```pip```
 * GPU models and configuration: 
```
 sudo lshw -C display
       description: VGA compatible controller
       product: UHD Graphics 620
       vendor: Intel Corporation
```

 * Python version
```
Python 3.8.10
```

 * PyTorch version
```
python3 -c "import torch; print(torch.__version__)"
1.6.0
```
 * Versions of any other relevant libraries (Pybullet, ...)

**Additional context**

**Comment by ebadi** [comment]
Solved. There is no issue when this part of the tqc.yml is commented out. 
```
  normalize: "{'norm_obs': True, 'norm_reward': False}"
  env_wrapper:
    - gym.wrappers.time_limit.TimeLimit:
        max_episode_steps: 10000
    - utils.wrappers.HistoryWrapper:
        horizon: 2
```
