### ISSUE TITLE
OpenCV error when enjoying Bullet env using Docker

### ISSUE THREAD

**Issue by ycps** [DLR-RM/rl-baselines3-zoo#23]
Hi, I'm not sure if I should put this here or in the SB3 main repo.

**Steps to reproduce**
```bash
git clone --recursive https://github.com/DLR-RM/rl-baselines3-zoo
cd rl-baselines3-zoo
make docker-cpu
./scripts/run_docker_cpu.sh python train.py --algo sac --env HumanoidBulletEnv-v0 --save-freq 1000
./scripts/run_docker_cpu.sh python enjoy.py --algo sac --env HumanoidBulletEnv-v0 -f logs/ --exp-id 1
```

**Output (of last command)**
```python
Executing in the docker (cpu image):
python enjoy.py --algo sac --env HumanoidBulletEnv-v0 -f logs/ --exp-id 1
+ export DISPLAY=:1
+ DISPLAY=:1
+ display=1
+ file=/tmp/.X11-unix/X1
+ sleep 1
+ Xvfb :1 -screen 0 1024x768x24
++ seq 1 10
+ for i in '$(seq 1 10)'
+ '[' -e /tmp/.X11-unix/X1 ']'
+ break
+ '[' -e /tmp/.X11-unix/X1 ']'
+ exec bash -c 'cd /root/code/rl_zoo/ && python enjoy.py --algo sac --env HumanoidBulletEnv-v0 -f logs/ --exp-id 1'
pybullet build time: Jun 19 2020 04:01:58
/opt/conda/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Loading running average
with params: {'norm_obs': True, 'norm_reward': False}
Traceback (most recent call last):
  File "enjoy.py", line 201, in <module>
    main()
  File "enjoy.py", line 138, in main
    env.render('human')
  File "/opt/conda/lib/python3.6/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 272, in render
    return self.venv.render(mode=mode)
  File "/opt/conda/lib/python3.6/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 272, in render
    return self.venv.render(mode=mode)
  File "/opt/conda/lib/python3.6/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 187, in render
    cv2.imshow('vecenv', bigimg[:, :, ::-1])
cv2.error: OpenCV(4.2.0) /io/opencv/modules/highgui/src/window.cpp:651: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'
```

**System Info**
Describe the characteristic of your environment:
 * Docker version 19.03.12
 * Host OS: Linux 5.3.0-59-generic #53~18.04.1-Ubuntu x86_64 GNU/Linux
 * CPU only

**Comment by araffin** [comment]
Hello,

you should use the `--no-render` option as docker does not support X-server.

**Comment by ycps** [comment]
Oops, I did not notice that. Thanks, araffin!
