### ISSUE TITLE
Error when using AutoEncoder and normalize

### ISSUE THREAD

**Issue by aazer00** [DLR-RM/rl-baselines3-zoo#230]
I try to train donkey car agent with AutoEncoder by following [DonkeyCar Simulator: Autoencoder training](https://www.youtube.com/watch?v=DUqssFvcSOY&ab_channel=AntoninRaffin) 

**Describe the bug**
Every thing works normal if I comment out normalize and env_wrapper in tqc.yml. But as soon as I add normile and Auto Encoder I get following errors.

For normalize: "{'norm_obs': True, 'norm_reward': False}":
ValueError: could not broadcast input array from shape (1,120,160,3) into shape (1,3,120,160)

And if with above line I add ae.wrapper.AutoencoderWrapper:
ValueError: too many values to unpack (expected 4)

**Code example**
```## Custom envs
donkey-mountain-track-v0:
    normalize: "{'norm_obs': True, 'norm_reward': False}"
    env_wrapper:
        - gym.wrappers.time_limit.TimeLimit:
              max_episode_steps: 10000
        - ae.wrapper.AutoencoderWrapper:
              ae_path: "D:\\Donkey Car\\RL\\aae-train-donkeycar\\logs\\ae-32_1649179759_best.pkl"
    #- utils.wrappers.HistoryWrapper:
    #      horizon: 2
    # - utils.wrappers.ResidualExpertWrapper:
    #     model_path: ./logs/human/donkey-generated-track-v0_2/policy.pt
    #     d3rlpy_model: True
    #     residual_scale: 0.5
    #     expert_scale: 1.0
    #- utils.wrappers.TimeFeatureWrapper:
    #    test_mode: False
    # - stable_baselines3.common.monitor.Monitor:
    #     filename: None
    callback:
        - utils.callbacks.ParallelTrainCallback:
              gradient_steps: 200
    # vec_env_wrapper:
    #   - utils.wrappers.VecForceResetWrapper
    n_timesteps: !!float 2e6
    policy: "MlpPolicy"
    learning_rate: !!float 7.3e-4
    #learning_rate: !!float 3e-4
    buffer_size: 20000
    batch_size: 256
    ent_coef: "auto"
    gamma: 0.99
    tau: 0.02
    # train_freq: [1, "episode"]
    train_freq: 200
    # gradient_steps: -1
    gradient_steps: 256
    learning_starts: 5000
    use_sde_at_warmup: True
    use_sde: True
    sde_sample_freq: 16
    policy_kwargs: "dict(log_std_init=-3, net_arch=[256, 256], n_critics=2)"
```

normalize error:
AutoEncoder Error:

```Seed: 2382948735
Default hyperparameters for environment (ones being tuned will be overridden):
OrderedDict([('batch_size', 256),
             ('buffer_size', 20000),
             ('callback',
              [{'utils.callbacks.ParallelTrainCallback': {'gradient_steps': 200}}]),
             ('ent_coef', 'auto'),
             ('env_wrapper',
              [{'gym.wrappers.time_limit.TimeLimit': {'max_episode_steps': 10000}}]),
             ('gamma', 0.99),
             ('gradient_steps', 256),
             ('learning_rate', 0.00073),
             ('learning_starts', 5000),
             ('n_timesteps', 2000000.0),
             ('normalize', "{'norm_obs': True, 'norm_reward': False}"),
             ('policy', 'MlpPolicy'),
             ('policy_kwargs',
              'dict(log_std_init=-3, net_arch=[256, 256], n_critics=2)'),
             ('sde_sample_freq', 16),
             ('tau', 0.02),
             ('train_freq', 200),
             ('use_sde', True),
             ('use_sde_at_warmup', True)])
Using 1 environments
starting DonkeyGym env
Setting default: start_delay 5.0
Setting default: max_cte 5.0
Setting default: frame_skip 1
Setting default: cam_resolution (120, 160, 3)
Setting default: log_level 20
Setting default: host localhost
Setting default: port 9091
INFO:gym_donkeycar.core.client:connecting to localhost:9091
D:\Anaconda\envs\test1\lib\site-packages\gym\spaces\box.py:74: UserWarning: WARN: Box bound precision lowered by casting to float32
  "Box bound precision lowered by casting to {}".format(self.dtype)
WARNING:gym_donkeycar.envs.donkey_sim:waiting for sim to start..
INFO:gym_donkeycar.envs.donkey_sim:on need car config
INFO:gym_donkeycar.envs.donkey_sim:sending car config.
Normalization activated: {'norm_obs': True, 'norm_reward': False, 'gamma': 0.99}
Wrapping the env in a VecTransposeImage.
Using cuda device
Log path: logs/tqc/donkey-mountain-track-v0_8
Traceback (most recent call last):
  File "train.py", line 294, in <module>
    exp_manager.learn(model)
  File "D:\Donkey Car\RL\rl-baselines3-zoo\utils\exp_manager.py", line 212, in learn
    model.learn(self.n_timesteps, **kwargs)
  File "D:\Anaconda\envs\test1\lib\site-packages\sb3_contrib\tqc\tqc.py", line 299, in learn
    reset_num_timesteps=reset_num_timesteps,
  File "D:\Anaconda\envs\test1\lib\site-packages\stable_baselines3\common\off_policy_algorithm.py", line 354, in learn
    log_interval=log_interval,
  File "D:\Anaconda\envs\test1\lib\site-packages\stable_baselines3\common\off_policy_algorithm.py", line 595, in collect_rollouts
    self._store_transition(replay_buffer, buffer_actions, new_obs, rewards, dones, infos)
  File "D:\Anaconda\envs\test1\lib\site-packages\stable_baselines3\common\off_policy_algorithm.py", line 513, in _store_transition
    infos,
  File "D:\Anaconda\envs\test1\lib\site-packages\stable_baselines3\common\buffers.py", line 246, in add
    self.observations[self.pos] = np.array(obs).copy()
ValueError: could not broadcast input array from shape (1,120,160,3) into shape (1,3,120,160)
```

```Seed: 443528640
Default hyperparameters for environment (ones being tuned will be overridden):
OrderedDict([('batch_size', 256),
             ('buffer_size', 20000),
             ('callback',
              [{'utils.callbacks.ParallelTrainCallback': {'gradient_steps': 200}}]),
             ('ent_coef', 'auto'),
             ('env_wrapper',
              [{'gym.wrappers.time_limit.TimeLimit': {'max_episode_steps': 10000}},
               {'ae.wrapper.AutoencoderWrapper': {'ae_path': 'D:\\Donkey '
                                                             'Car\\RL\\aae-train-donkeycar\\logs\\ae-32_1649179759_best.pkl'}}]),
             ('gamma', 0.99),
             ('gradient_steps', 256),
             ('learning_rate', 0.00073),
             ('learning_starts', 5000),
             ('n_timesteps', 2000000.0),
             ('normalize', "{'norm_obs': True, 'norm_reward': False}"),
             ('policy', 'MlpPolicy'),
             ('policy_kwargs',
              'dict(log_std_init=-3, net_arch=[256, 256], n_critics=2)'),
             ('sde_sample_freq', 16),
             ('tau', 0.02),
             ('train_freq', 200),
             ('use_sde', True),
             ('use_sde_at_warmup', True)])
Using 1 environments
starting DonkeyGym env
Setting default: start_delay 5.0
Setting default: max_cte 5.0
Setting default: frame_skip 1
Setting default: cam_resolution (120, 160, 3)
Setting default: log_level 20
Setting default: host localhost
Setting default: port 9091
INFO:gym_donkeycar.core.client:connecting to localhost:9091
D:\Anaconda\envs\test1\lib\site-packages\gym\spaces\box.py:74: UserWarning: WARN: Box bound precision lowered by casting to float32
  "Box bound precision lowered by casting to {}".format(self.dtype)
WARNING:gym_donkeycar.envs.donkey_sim:waiting for sim to start..
INFO:gym_donkeycar.envs.donkey_sim:on need car config
INFO:gym_donkeycar.envs.donkey_sim:sending car config.
Dim AE = 32
PyTorch 1.11.0
Normalization activated: {'norm_obs': True, 'norm_reward': False, 'gamma': 0.99}
Using cuda device
Log path: logs/tqc/donkey-mountain-track-v0_7
Traceback (most recent call last):
  File "train.py", line 294, in <module>
    exp_manager.learn(model)
  File "D:\Donkey Car\RL\rl-baselines3-zoo\utils\exp_manager.py", line 212, in learn
    model.learn(self.n_timesteps, **kwargs)
  File "D:\Anaconda\envs\test1\lib\site-packages\sb3_contrib\tqc\tqc.py", line 299, in learn
    reset_num_timesteps=reset_num_timesteps,
  File "D:\Anaconda\envs\test1\lib\site-packages\stable_baselines3\common\off_policy_algorithm.py", line 354, in learn
    log_interval=log_interval,
  File "D:\Anaconda\envs\test1\lib\site-packages\stable_baselines3\common\off_policy_algorithm.py", line 580, in collect_rollouts
    new_obs, rewards, dones, infos = env.step(actions)
  File "D:\Anaconda\envs\test1\lib\site-packages\stable_baselines3\common\vec_env\base_vec_env.py", line 162, in step
    return self.step_wait()
  File "D:\Anaconda\envs\test1\lib\site-packages\stable_baselines3\common\vec_env\vec_normalize.py", line 149, in step_wait
    obs, rewards, dones, infos = self.venv.step_wait()
  File "D:\Anaconda\envs\test1\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 44, in step_wait
    self.actions[env_idx]
ValueError: too many values to unpack (expected 4)

```

**Comment by araffin** [comment]
Hello,
I just uploaded the code here: https://github.com/araffin/aae-train-donkeycar/pull/3 
Please use that one, there is probably something wrong in your wrapper code, the shape of the input observation does not look right at all (it should be a vector, not an image).

More info: https://github.com/araffin/aae-train-donkeycar/releases/tag/live-twitch-2

**Comment by aazer00** [comment]
> Hello, I just uploaded the code here: [araffin/aae-train-donkeycar#3](https://github.com/araffin/aae-train-donkeycar/pull/3) Please use that one, there is probably something wrong in your wrapper code, the shape of the input observation does not look right at all (it should be a vector, not an image).
> 
> More info: https://github.com/araffin/aae-train-donkeycar/releases/tag/live-twitch-2

It worked. Thank you very much.
