### ISSUE TITLE
`train_eval_metrics.zip` not found for Cartpole-v1

### ISSUE THREAD

**Issue by qgallouedec** [DLR-RM/rl-baselines3-zoo#252]
Hello,

I encounter the following error when I run the hugging face demo line from the `README.md`.

```bash
python -m utils.load_from_hub --algo ppo --env CartPole-v1 -f logs/ -orga sb3
```

```log
Downloading from https://huggingface.co/sb3/ppo-CartPole-v1
No normalization file
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.13/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.13/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/quentingallouedec/rl-baselines3-zoo/utils/load_from_hub.py", line 50, in <module>
    train_eval_metrics = load_from_hub(repo_id, "train_eval_metrics.zip")
  File "/Users/quentingallouedec/rl-baselines3-zoo/.env/lib/python3.9/site-packages/huggingface_sb3/load_from_hub.py", line 16, in load_from_hub
    downloaded_model_file = hf_hub_download(
  File "/Users/quentingallouedec/rl-baselines3-zoo/.env/lib/python3.9/site-packages/huggingface_hub/utils/_deprecation.py", line 32, in inner_f
    return f(*args, **kwargs)
  File "/Users/quentingallouedec/rl-baselines3-zoo/.env/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 778, in hf_hub_download
    return cached_download(
  File "/Users/quentingallouedec/rl-baselines3-zoo/.env/lib/python3.9/site-packages/huggingface_hub/utils/_deprecation.py", line 32, in inner_f
    return f(*args, **kwargs)
  File "/Users/quentingallouedec/rl-baselines3-zoo/.env/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 554, in cached_download
    r.raise_for_status()
  File "/Users/quentingallouedec/rl-baselines3-zoo/.env/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/sb3/ppo-CartPole-v1/resolve/main/train_eval_metrics.zip
```

I checked  the repo https://huggingface.co/sb3. Indeed, for some environments, including `CartPole-v1`, there isn't any `train_eval_metrics.zip` file.

**Comment by araffin** [comment]
Hello,
thanks for reporting the issue, the agent was uploaded with older version of push to hub, will update it soon ;)

**Comment by araffin** [comment]
Fixed https://huggingface.co/sb3/ppo-CartPole-v1 ;)
