### ISSUE TITLE
hyperparameter optimization with customised environment

### ISSUE THREAD

**Issue by blurLake** [DLR-RM/rl-baselines3-zoo#27]
Hi, first question I have is that is it possible to run hyperparameter optimization using customised environment? If possible, what should be the file structure for train.py to recognize the environment. I have tried the following structure 
```
│   train.py    
|   setup.py
│
└───gym_environment/
│   │   envs/
│   │   __init__.py
``` 
where `__init__.py` registers 
```  
    id='FullFilterEnv-v0',
    entry_point='gym_environment.envs:FullFilterEnv',
    max_episode_steps=10,
```
Then I run 
`python train.py --algo td3 --env FullFilterEnv-v0 -n 50000 -optimize --n-trials 1000 --n-jobs 2 --sampler random --pruner median
`.  
But the following error pops up 
`ValueError: FullFilterEnv-v0 not found in gym registry, you maybe meant AntBulletEnv-v0?`

Should I put the env into the yml file in hyperparams/ ? Perhaps a good example in the documents would be helpful. 

Thanks a lot!

**System Info**
 * stable-baselines3-0.8.0a0

**Comment by araffin** [comment]
> run hyperparameter optimization using customised environment?

Yes, it is totally possible, in fact we are already doing that for pybullet envs.
Best is to create a python package and import it in `utils/import_envs.py`.
Otherwise, you can use ` --gym-packages package_name`, see https://github.com/DLR-RM/rl-baselines3-zoo#minigrid-envs

>Should I put the env into the yml file in hyperparams/

You should also do that too.

Related: https://github.com/araffin/rl-baselines-zoo/issues/29

**Comment by blurLake** [comment]
Thanks for your reply! Do I understand it correctly that the parameters set in yml file in hyperparams/ gives initial value for the optimization algorithm, and the rest of the hyperparameters for each algorithm, say TD3, will take the default value. Moreover, the hyperparameter optimization will only optimize wrt the ones in yml, while others are not changed at all. 

Also, I saw, in `hyperparams_opt.py` there is suggested value, e.g., gamma has [0.9, 0.95, 0.999...]. Is the optimization algorithm only searching within these suggested values? For example, can gamma = 0.1 be optimal eventually?

**Comment by araffin** [comment]
>Do I understand it correctly that the parameters set in yml file in hyperparams/ gives initial value for the optimization algorithm, and the rest of the hyperparameters for each algorithm, say TD3, will take the default value. Moreover, the hyperparameter optimization will only optimize wrt the ones in yml, while others are not changed at all.

Almost. When optimizing hyperparameters, we don't optimize everything, otherwise the search space would be too big, and you also need to specify the budget (number of timesteps) and the type of policy.
You can define some custom value in the yaml file, however, for the one that are optimized, there are going to be overwritten.
In the future, it would be nice to add the hyperparameters in the yaml file to the queue of hyperparameters to be tested (I think optuna added that feature recently).
Sorry for the confusion, I think this is related to #14 second point.


>Also, I saw, in hyperparams_opt.py there is suggested value, e.g., gamma has [0.9, 0.95, 0.999...]. Is the optimization algorithm only searching within these suggested values? For example, can gamma = 0.1 be optimal eventually?

Yes, it is only searching with these values. For the same reason as before, this allow to restrict the search space and those values usually gives the best results.

>For example, can gamma = 0.1 be optimal eventually?

If by optimal you mean reaching the maximum performance quickly, yes it can, but in practice you rarely see a gamma with a value below 0.9. If you have some knowledge about the range of optimal values, then you can change them ;)

**Comment by blurLake** [comment]
Hi, thank you for your comments. I managed to use zoo to my own environment in my macOs laptop and everything works well. But when I migrate to a VM using Ubuntu 18.04.1 LTS, the following error pops up. Do you have any suggestions?

Thank you!

  
``` Trial 0 failed because of the following error: TypeError('should_prune() takes 1 positional argument but 2 were given',)
Traceback (most recent call last):
  File "/home/eejiiew/filter-zoo/venv/lib/python3.6/site-packages/optuna/study.py", line 709, in _run_trial
    result = func(trial)
  File "/home/eejiiew/filter-zoo/rl-baselines3-zoo/utils/hyperparams_opt.py", line 95, in objective
    model.learn(n_timesteps, callback=eval_callback)
  File "/home/eejiiew/filter-zoo/venv/lib/python3.6/site-packages/stable_baselines3/td3/td3.py", line 198, in learn
    reset_num_timesteps=reset_num_timesteps,
  File "/home/eejiiew/filter-zoo/venv/lib/python3.6/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 253, in learn
    log_interval=log_interval,
  File "/home/eejiiew/filter-zoo/venv/lib/python3.6/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 406, in collect_rollouts
    if callback.on_step() is False:
  File "/home/eejiiew/filter-zoo/venv/lib/python3.6/site-packages/stable_baselines3/common/callbacks.py", line 92, in on_step
    return self._on_step()
  File "/home/eejiiew/filter-zoo/rl-baselines3-zoo/utils/callbacks.py", line 33, in _on_step
    if self.trial.should_prune(self.eval_idx):
TypeError: should_prune() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "train.py", line 392, in <module>
    storage=args.storage, study_name=args.study_name, verbose=args.verbose)
  File "/home/eejiiew/filter-zoo/rl-baselines3-zoo/utils/hyperparams_opt.py", line 119, in hyperparam_optimization
    study.optimize(objective, n_trials=n_trials, n_jobs=n_jobs)
  File "/home/eejiiew/filter-zoo/venv/lib/python3.6/site-packages/optuna/study.py", line 292, in optimize
    func, n_trials, timeout, catch, callbacks, gc_after_trial, None
  File "/home/eejiiew/filter-zoo/venv/lib/python3.6/site-packages/optuna/study.py", line 654, in _optimize_sequential
    self._run_trial_and_callbacks(func, catch, callbacks, gc_after_trial)
  File "/home/eejiiew/filter-zoo/venv/lib/python3.6/site-packages/optuna/study.py", line 685, in _run_trial_and_callbacks
    trial = self._run_trial(func, catch, gc_after_trial)
  File "/home/eejiiew/filter-zoo/venv/lib/python3.6/site-packages/optuna/study.py", line 709, in _run_trial
    result = func(trial)
  File "/home/eejiiew/filter-zoo/rl-baselines3-zoo/utils/hyperparams_opt.py", line 95, in objective
    model.learn(n_timesteps, callback=eval_callback)
  File "/home/eejiiew/filter-zoo/venv/lib/python3.6/site-packages/stable_baselines3/td3/td3.py", line 198, in learn
    reset_num_timesteps=reset_num_timesteps,
  File "/home/eejiiew/filter-zoo/venv/lib/python3.6/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 253, in learn
    log_interval=log_interval,
  File "/home/eejiiew/filter-zoo/venv/lib/python3.6/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 406, in collect_rollouts
    if callback.on_step() is False:
  File "/home/eejiiew/filter-zoo/venv/lib/python3.6/site-packages/stable_baselines3/common/callbacks.py", line 92, in on_step
    return self._on_step()
  File "/home/eejiiew/filter-zoo/rl-baselines3-zoo/utils/callbacks.py", line 33, in _on_step
    if self.trial.should_prune(self.eval_idx):
TypeError: should_prune() takes 1 positional argument but 2 were given```

**Comment by blurLake** [comment]
This is a version conflict. The error can be resolved either by downgrade optuna to 1.5.0, or do the modification in SB-zoo as in [here](https://github.com/DLR-RM/rl-baselines3-zoo/commit/3c0dec8abf91c1aac4547b1bc4be7ac8ebd052e4) about utils/callbacks.py.

**Comment by araffin** [comment]
this was fixed in https://github.com/DLR-RM/rl-baselines3-zoo/pull/36
please update your rl zoo

**Comment by araffin** [comment]
Closing this as the original question was answered.
