### ISSUE TITLE
DQN + Atari Not working

### ISSUE THREAD

**Issue by alramalho** [DLR-RM/rl-baselines3-zoo#270]
**Describe the bug**
DQN doesn't seem to be succesfully training on Atari Gym enviroments, it fails with the error
```
...
ValueError: ReplayBuffer does not support optimize_memory_usage = True and handle_timeout_termination = True simultaneously.
```

I've looked through the docs and doesn't seem that I am missing anything. Apologies if I do.

**Code example**
Gives error:
`python3 train.py --algo dqn  --env SpaceInvadersNoFrameskip-v4 -f logs/ -n 1000000`
Doesn't give error:
`python3 train.py --algo a2c  --env SpaceInvadersNoFrameskip-v4 -f logs/ -n 1000000`
Doesn't give error:
`python3 train.py --algo dqn  --env CartPole-v1 -f logs/ -n 1000000`

**System Info**
Describe the characteristic of your environment:
 * Describe how Stable Baselines3 was installed (pip, docker, source, ...)
 * GPU models and configuration: macOS Big Sur 11.6.6
 * Python version: 3.9.13
 * PyTorch version: 1.11.0

**Additional context**
```
Traceback (most recent call last):
  File "/Users/alramalho/workspace/rl-baselines3-zoo/train.py", line 231, in <module>
    results = exp_manager.setup_experiment()
  File "/Users/alramalho/workspace/rl-baselines3-zoo/utils/exp_manager.py", line 189, in setup_experiment
    model = ALGOS[self.algo](
  File "/Users/alramalho/workspace/stable-baselines3/stable_baselines3/dqn/dqn.py", line 138, in __init__
    self._setup_model()
  File "/Users/alramalho/workspace/stable-baselines3/stable_baselines3/dqn/dqn.py", line 141, in _setup_model
    super()._setup_model()
  File "/Users/alramalho/workspace/stable-baselines3/stable_baselines3/common/off_policy_algorithm.py", line 205, in _setup_model
    self.replay_buffer = self.replay_buffer_class(
  File "/Users/alramalho/workspace/stable-baselines3/stable_baselines3/common/buffers.py", line 195, in __init__
    raise ValueError(
ValueError: ReplayBuffer does not support optimize_memory_usage = True and handle_timeout_termination = True simultaneously.

```

**Comment by araffin** [comment]
I pushed a fix here https://github.com/DLR-RM/rl-baselines3-zoo/pull/271
