### ISSUE TITLE
Errors in record_video.py due to having both optimize_memory_usage and handle_timeout_termination

### ISSUE THREAD

**Issue by Affonso-Gui** [DLR-RM/rl-baselines3-zoo#279]
**Describe the bug**
The same bug as #270 , but when running utils/record_video.py.

**Code example**
```bash
python -m utils.record_video --algo dqn --env PongNoFrameskip-v4 -f rl-trained-agents/ -n 10000
```

Then the tracing:
```
Traceback (most recent call last):
  File "/opt/conda/envs/project-plb/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/project-plb/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/rl-baselines3-zoo/utils/record_video.py", line 118, in <module>
    model = ALGOS[algo].load(model_path, env=env, custom_objects=custom_objects, **kwargs)
  File "/opt/conda/envs/project-plb/lib/python3.10/site-packages/stable_baselines3/common/base_class.py", line 747, in load
    model._setup_model()
  File "/opt/conda/envs/project-plb/lib/python3.10/site-packages/stable_baselines3/dqn/dqn.py", line 141, in _setup_model
    super()._setup_model()
  File "/opt/conda/envs/project-plb/lib/python3.10/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 205, in _setup_model
    self.replay_buffer = self.replay_buffer_class(
  File "/opt/conda/envs/project-plb/lib/python3.10/site-packages/stable_baselines3/common/buffers.py", line 195, in __init__
    raise ValueError(
ValueError: ReplayBuffer does not support optimize_memory_usage = True and handle_timeout_termination = True simultaneously.
```

**System Info**
Python 3.10.5
PyTorch 1.12.1
SB3 1.6.0

**Solution**
I have solved this by forcing `optimize_memory_usage` to False, as in #271.  
(https://github.com/Affonso-Gui/rl-baselines3-zoo/commit/e9ebe90f9797c3bd4995ae191ada1fa745144ca7)
Should we consider doing the same on the master branch?

**Comment by araffin** [comment]
Hello,

I would be happy to receive a PR that fix that issue ;) (but not for push to hub, push to hub should be used on the machine that trained the model).

Could you also add https://github.com/DLR-RM/rl-baselines3-zoo/pull/274/commits/a27340a690395d3d536c6b21d3f31a36ca180cd0 to record video?

**Comment by Affonso-Gui** [comment]
@araffin Great, will organize and send the PR in a second! (I was wondering about the push to hub, glad you clarified it)
