### ISSUE TITLE
[Bug]: enjoy tries to access huggingface

### ISSUE THREAD

**Issue by Melanol** [DLR-RM/rl-baselines3-zoo#382]
### 🐛 Bug

Even though I can see the model in the rl-trained-agents folder.

### To Reproduce

```shell
python enjoy.py --algo a2c --env CartPole-v1_1 --folder rl-trained-agents/ -n 5000
```

### Relevant log output / Error message

```shell
Loading latest experiment, id=0
Pretrained model not found, trying to download it from sb3 Huggingface hub: https://huggingface.co/sb3
Downloading from https://huggingface.co/sb3/a2c-CartPole-v1_1
Traceback (most recent call last):
  File "/home/mel/PycharmProjects/rl-baselines3-zoo/rl_zoo3/enjoy.py", line 87, in enjoy
    _, model_path, log_path = get_model_path(
  File "/home/mel/PycharmProjects/rl-baselines3-zoo/rl_zoo3/utils.py", line 507, in get_model_path
    raise ValueError(f"No model found for {algo} on {env_name}, path: {model_path}")
ValueError: No model found for a2c on CartPole-v1_1, path: rl-trained-agents/a2c/CartPole-v1_1.zip

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mel/PycharmProjects/rl-baselines3-zoo/venv/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/home/mel/PycharmProjects/rl-baselines3-zoo/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/sb3/a2c-CartPole-v1_1/resolve/main/a2c-CartPole-v1_1.zip

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mel/PycharmProjects/rl-baselines3-zoo/enjoy.py", line 4, in <module>
    enjoy()
  File "/home/mel/PycharmProjects/rl-baselines3-zoo/rl_zoo3/enjoy.py", line 104, in enjoy
    download_from_hub(
  File "/home/mel/PycharmProjects/rl-baselines3-zoo/rl_zoo3/load_from_hub.py", line 48, in download_from_hub
    checkpoint = load_from_hub(repo_id, model_name.filename)
  File "/home/mel/PycharmProjects/rl-baselines3-zoo/venv/lib/python3.10/site-packages/huggingface_sb3/load_from_hub.py", line 16, in load_from_hub
    downloaded_model_file = hf_hub_download(
  File "/home/mel/PycharmProjects/rl-baselines3-zoo/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/mel/PycharmProjects/rl-baselines3-zoo/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1195, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/mel/PycharmProjects/rl-baselines3-zoo/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/mel/PycharmProjects/rl-baselines3-zoo/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1541, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/home/mel/PycharmProjects/rl-baselines3-zoo/venv/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 291, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-64808066-04dedf24470933db6bd01759)

Repository Not Found for url: https://huggingface.co/sb3/a2c-CartPole-v1_1/resolve/main/a2c-CartPole-v1_1.zip.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
```

### System Info

- OS: Linux-5.19.0-43-generic-x86_64-with-glibc2.35 # 44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2
- Python: 3.10.6
- Stable-Baselines3: 2.0.0a10
- PyTorch: 2.0.1+cu117
- GPU Enabled: True
- Numpy: 1.24.3
- Cloudpickle: 2.2.1
- Gymnasium: 0.28.1
- OpenAI Gym: 0.26.2

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo documentation](https://rl-baselines3-zoo.readthedocs.io)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by Melanol** [comment]
> Can you confirm that the following command does not throw an error?

AssertionError: File does not exist.

**Comment by Melanol** [comment]
> you have a typo: `--env CartPole-v1_1` -> `--env CartPole-v1`

This happened because I went browsing the rl-trained-agents folder. Maybe `enjoy` should check for this mistake for dummies like me.
