### ISSUE TITLE
[Question] You must pass an environment when using `HerReplayBuffer`

### ISSUE THREAD

**Issue by moneypi** [DLR-RM/rl-baselines3-zoo#432]
### ❓ Question

I try to train parking-v0 with command
`python train.py --algo tqc --env parking-v0`
and everything seems fine.
![20240118-152847](https://github.com/DLR-RM/rl-baselines3-zoo/assets/27052490/9cc1c507-635e-44ae-b4d1-9fa3fe962adf)
and I try to run `python enjoy.py --algo tqc --env parking-v0 --folder logs/tqc/parking-v0_1/`， I get errors as follow,
![20240118-153105](https://github.com/DLR-RM/rl-baselines3-zoo/assets/27052490/bf073c92-b738-4e39-ba84-cd916c5afee1)

and I try to fix it by 
```
cd logs/tqc/parking-v0_1
mkdir tqc
cp best_model.zip tqc/parking-v0.zip
```
and when I ran `python enjoy.py --algo tqc --env parking-v0 --folder logs/tqc/parking-v0_1/` again, I get errors as follow
```
(base) zhuqinghua@lcwt-DSS8440:~/workspace/rl-baselines3-zoo-master$ python enjoy.py --algo tqc --env parking-v0 --folder logs/tqc/parking-v0_1/
Loading latest experiment, id=0
Loading logs/tqc/parking-v0_1/tqc/parking-v0.zip
Traceback (most recent call last):
  File "enjoy.py", line 4, in <module>
    enjoy()
  File "/home/zhuqinghua/workspace/rl-baselines3-zoo-master/rl_zoo3/enjoy.py", line 192, in enjoy
    model = ALGOS[algo].load(model_path, custom_objects=custom_objects, device=args.device, **kwargs)
  File "/home/zhuqinghua/miniconda3/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 737, in load
    model._setup_model()
  File "/home/zhuqinghua/miniconda3/lib/python3.8/site-packages/sb3_contrib/tqc/tqc.py", line 153, in _setup_model
    super()._setup_model()
  File "/home/zhuqinghua/miniconda3/lib/python3.8/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 187, in _setup_model
    assert self.env is not None, "You must pass an environment when using `HerReplayBuffer`"
AssertionError: You must pass an environment when using `HerReplayBuffer`
```
Am I wrong in any step?
How can I fix the error?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo documentation](https://rl-baselines3-zoo.readthedocs.io)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by moneypi** [comment]
`python enjoy.py --algo tqc --env parking-v0 -f logs/ --exp-id 0`
